src/Groq/components/Combine.tsx

Just realized a file `./components/Combine.tsx` was missing in #13 . Had to open another one to add the file.

🐛 fix: add Combine.tsx file

---

src/ModelIcon/const.ts

🐛 fix: fix doubao model icon

---

src/ModelIcon/const.ts
src/ProviderIcon/const.ts

 💄 style: Add Doubao Model

---

src/ModelIcon/const.ts

💄 style: upload pixtral model icon

---

src/ModelIcon/const.ts

refs: https://github.com/lobehub/lobe-chat/pull/4071

💄 style: support Spark Max-32k

---

src/features/modelConfig.ts

💄 style: add modelIcon support Ministral model from Mistral

---

src/features/modelConfig.ts

讯飞改变了 Spark Lite 的 ID，`general` -> `lite`

💄 style: add support for Spark Lite modelIcon (New model ID: `lite`)

---

src/features/providerConfig.tsx

Add Workers AI Icon to Cloudflare Combine
Originally by @sxjeru.

💄 style: Add WorkersAI to Cloudflare

---

src/features/modelConfig.ts

💄 style: fix `phi-2` model icon in CF `@cf/microsoft/phi-2`

---

src/features/modelConfig.ts

https://huggingface.co/Qwen/QVQ-72B-Preview

💄 style: 适配 Qwen/QVQ 模型图标

---

src/features/providerConfig.tsx
src/features/providerEnum.ts

:lipstick: style: add nvidia as provider

---

src/features/modelConfig.ts

:lipstick: style: add jina deep search icons

---

src/features/modelConfig.ts

适配 Moonshot `kimi-latest` 模型图标

💄 style: add `kimi-latest` icon support

---

src/features/providerConfig.tsx
src/features/providerEnum.ts

https://github.com/lobehub/lobe-chat/pull/7016

💄 style: support cohere provider

---

src/features/modelConfig.ts

1. 增加对 `SenseNova-V6` 系列模型图标的适配

💄 style: add `SenseNova-V6` series icon support

---

src/features/modelConfig.ts

💄 style: support o4 icons

---

src/features/modelConfig.ts

💄 style: support Spark X1 icons

---

src/features/providerConfig.tsx
src/features/providerEnum.ts

✨ feat: support fal provider icon and combine

---

src/features/modelConfig.ts
src/features/providerConfig.tsx
src/features/providerEnum.ts

💄 style: add aihubmix

---

package.json

💄 style: upgrade react-layout-kit

---

package.json

🐛 fix: Ci build error

---

src/features/modelConfig.ts

https://docs.mistral.ai/getting-started/models/models_overview/

💄 style: Update Mistral AI model logo
